config/routes.rb
Rails.application.routes.draw do
  resources :permission_codes
  resources :workers
  resources :tasks
  resources :jobs
  resources :users
  resources :sub_contractors

  root 'jobs#index'
  get '/login', to: 'sessions#new'
  post "/login", to: "sessions#create"
  delete "/login", to: "sessions#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sub_contractor.rb
class SubContractor < ApplicationRecord
  validates :name,
    presence: true,
    uniqueness: true
  
  has_many :tasks
  has_many :jobs, through: :tasks
  has_many :workers, dependent: :destroy
end

app/controllers/sub_contractors_controller.rb
class SubContractorsController < ApplicationController
  before_action :set_sub_contractor, only: [:show, :edit, :update, :destroy]
  
  def index
    @sub_contractors = logged_in? ? SubContractor.all : []
  end
  def show
  end
  def new
    @sub_contractor = SubContractor.new
  end
  def create
    @sub_contractor = SubContractor.new(sub_contractor_params)

    respond_to do |format|
      if logged_in?
        if @sub_contractor.save
          format.html { redirect_to @sub_contractor, notice: 'Created subcontractor successfully' }
          format.json { render :show, location: @sub_contractor, status: :created }
        else
          format.html { render :new }
          format.json { render json: @sub_contractor.errors, status: :unprocessable_entity }
        end
      else
        @sub_contractor.errors.add(:_, 'Only logged in users can add new subcontractors.')
        format.html { render :new }
        format.json { render json: @sub_contractor.errors, status: :unauthorized }
      end
    end
  end
  def edit
  end
  def update
    respond_to do |format|
      if logged_in?
        if @sub_contractor.update(sub_contractor_params)
          format.html { redirect_to @sub_contractor, notice: 'Updated subcontractor succesfully.' }
          format.json { render :show, location: @sub_contractor, status: :ok }
        else
          format.html { render :edit }
          format.json { render json: @sub_contractor.errors, status: :unprocessable_entity }
        end
      else
        @sub_contractor.errors.add(:_, 'Only logged in users can edit sub contractors')
        format.html { render :edit }
        format.json { render json: @sub_contractor.errors, status: :unauthorized }
      end
    end
  end
  def destroy
    respond_to do |format|
      if logged_in?
        @sub_contractor.destroy

        format.html { render :index, notice: 'Delete subcontractor successfully' }
        format.json { head :no_content }
      else
        @sub_contractor.errors.add(:_, 'Only logged in users can delete subcontractors')
        
        format.html { render :edit, location: @sub_contractor }
        format.json { render json: @sub_contractor.errors, status: :unauthorized }
      end
    end
  end

  private

  def set_sub_contractor
    return nil if !params[:id]

    @sub_contractor = SubContractor.find(params[:id])
  end 
  def sub_contractor_params
    params.require(:sub_contractor).permit(
      :name
    )
  end
end

app/helpers/sub_contractors_helper.rb
module SubContractorsHelper
end

app/views/sub_contractors/_form.html.erb
<%= form_with(model: sub_contractor, local: true) do |form|%>
  <% if sub_contractor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sub_contractor.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% sub_contractor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </p>

  <%= form.submit 'Create Subcontractor' %>
<% end %>

app/views/sub_contractors/edit.html.erb
<h1>New Subcontractor</h1>

<% if logged_in? %>
  <%= render 'form', sub_contractor: @sub_contractor %>
<% else %>
  <i>You are not allowed to create users</i>
<% end %>

<br>

<%= link_to 'All Subcontractors', sub_contractors_path %>

app/views/sub_contractors/index.html.erb
<h1>Subcontractors</h1>

<% if !logged_in? %> 
  <i>You are not logged in</i>
<% elsif @sub_contractors.any? %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Tasks</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% @sub_contractors.each do |sub_contractor| %>
        <tr>
          <td><%= link_to sub_contractor.name, sub_contractor %></td>
          <td><%= sub_contractor.tasks.length %></td>
          <td><%= link_to 'Edit', edit_sub_contractor_path(sub_contractor) %></td>
          <td><%= link_to 'Destroy', sub_contractor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'Create new subcontractor', new_sub_contractor_path %>
<% else %>
  <i>There are no subcontractors available</i>
<% end %>

app/views/sub_contractors/new.html.erb
<h1>New Subcontractor</h1>

<% if logged_in? %>
  <%= render 'form', sub_contractor: @sub_contractor %>
<% else %>
  <i>You are not allowed to create users</i>
<% end %>

<br>

<%= link_to 'All Subcontractors', sub_contractors_path %>

app/views/sub_contractors/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Subcontractor: <%= @sub_contractor.name %></h2>

<% if logged_in? %>
  <%= link_to 'Edit', edit_sub_contractor_path(@sub_contractor) %> |
  <%= link_to 'Destroy', @sub_contractor, method: :destroy, data: { confirm: 'Are you sure?' } %>
  <br>
<% end%>

<h3>Tasks:</h3>
<% if @sub_contractor.tasks.any? %>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Job</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @sub_contractor.tasks.each do |task| %>
        <% next if !current_user_has_low_permission_for_job(task.job) %>
        <tr>
          <td><%= task.title %></td>
          <td><%= link_to task.job.title, task.job %></td>
          <td><%= link_to 'Show', task %></td>
          <td><%= link_to 'Edit', edit_task_path(task) %></td>
          <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <i>This subcontractor has no tasks
<% end %>

<br/>
<%= link_to 'New Task', new_task_path %>
<br/>

<h3>Workers (<%= @sub_contractor.workers.length %>):</h3>
<% if @sub_contractor.workers.any? %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Pay</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @sub_contractor.workers.each do |worker| %>
        <tr>
          <td><%= link_to "#{worker.last_name}, #{worker.first_name}", worker %></td>
          <td><%= "$#{worker.pay}" %></td>
          <td><%= link_to 'Show', worker %></td>
          <td><%= link_to 'Edit', edit_worker_path(worker) %></td>
          <td><%= link_to 'Destroy', worker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <i>This job has no workers</i>
<% end %>

<br/>

<%= link_to 'New Worker', new_worker_path %>
<br>
<%= link_to 'All Subcontractors', sub_contractors_path %>