config/routes.rb
Rails.application.routes.draw do
  resources :permission_codes
  resources :workers
  resources :tasks
  resources :jobs
  resources :users
  resources :sub_contractors

  root 'jobs#index'
  get '/login', to: 'sessions#new'
  post "/login", to: "sessions#create"
  delete "/login", to: "sessions#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
  validates :title,
    presence: true,
    length: { minimum: 1, maximum: 255 }

  validates :start_date,
    presence: true

  validates :project_manager_id, # jobs need a project manager
    presence: true

  belongs_to :superintendent, foreign_key: 'superintendent_id', class_name: 'User'
  belongs_to :project_manager, foreign_key: 'project_manager_id', class_name: 'User'

  has_many :tasks, dependent: :destroy
  has_many :sub_contractors, -> { distinct }, through: :tasks
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :set_users, only: [:new, :create, :edit, :update]
  # GET /jobs
  # GET /jobs.json
  def index
    # make sure we can view jobs when delivering them
    @jobs = (Job.all).reject{|j| !current_user_has_low_permission_for_job(j)}
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    
    # the project manager chosen by admin creating this job ... OR
    project_manager_provided = params[:job][:project_manager_id] if current_user_is_admin
    # ... the project manager creating this job
    automatic_project_manager = current_user if current_user_is_project_manager

    if project_manager_provided
      @job.project_manager_id = project_manager_provided
    elsif automatic_project_manager
      @job.project_manager_id = automatic_project_manager.id
    end

    superintendent_exists = User.exists?(@job.superintendent_id)

    respond_to do |format|
      if current_user_has_high_permission_for_job and superintendent_exists
        if @job.save
          puts @job
          format.html { redirect_to @job, notice: 'Job was successfully created.' }
          format.json { render :show, status: :created, location: @job }
        else
          format.html { render :new }
          format.json { render json: @job.errors, status: :unprocessable_entity }
        end
      elsif !superintendent_exists
        @job.errors.add(:_, 'This superintendent does not exist')

        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      elsif !current_user_has_high_permission_for_job
        @job.errors.add(:_, 'You dont have permission to create a job')

        format.html { render :new }
        format.json { render json: @job.errors, status: :unauthorized }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if current_user_has_high_permission_for_job(@job)
        if @job.update(job_params)
          format.html { redirect_to @job, notice: 'Job was successfully updated.' }
          format.json { render :show, status: :ok, location: @job }
        else
          format.html { render :edit }
          format.json { render json: @job.errors, status: :unprocessable_entity }
        end
      else
        @job.errors.add(:_, 'You do not have permission to update jobs')

        format.html { render :index }
        format.json { render json: @job.errors, status: :unauthorized }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    respond_to do |format|
      if current_user_has_high_permission_for_job(@job)
        @job.destroy

        format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { render :index, notice: 'You cannot destroy jobs' }
        format.json { render json: @job.errors, status: :unauthorized }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      return nil if !params[:id]

      selected_job = Job.find(params[:id])

      @job = selected_job if current_user_has_low_permission_for_job(selected_job)
    end

    def set_users
      @superintendents = Array(User.where(role: 3))
      @project_managers = Array(User.where(role: 2))
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(
        :title,
        :superintendent_id,
        :start_date,
        :end_date
      )
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.datetime_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.datetime_select :end_date %>
  </div>
  
  <% if current_user_is_admin %>
    <% if @project_managers.any? %>
      <%= form.label 'Project manager' %>
      <%= form.select :project_manager_id, options_for_select(
        @project_managers.map {|p| ["#{p.first_name} #{p.last_name}", p.id]},
        @job.project_manager_id
      ) %>
    <% else %>
      <i>There are no project managers available!</i>
    <% end %>
  <% end %>

  <%= form.label 'Superintendent' %>
  <%= form.select :superintendent_id, options_for_select(
    @superintendents.map {|s| ["#{s.first_name} #{s.last_name}", s.id]},
    @job.superintendent_id
  ) %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<% if current_user_has_high_permission_for_job %>
  <%= render 'form', job: @job %>

  <%= link_to 'Show', @job %> |
<% else %>
  <i>You do not have permission to see this job</i>
<% end %>
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<% if logged_in? && !current_user_is_admin %>
  <h1>My Jobs</h1>
<% else %>
  <h1>Jobs</h1>
<% end %>

<% if @jobs.any? %>
  <table>
    <thead>
      <tr>
        <th>Job</th>
        <th>Manager</th>
        <th>Superintendent</th>
        <th>Start date</th>
        <th>End date</th>
        <th>Tasks</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @jobs.each do |job| %>
        <% next if !current_user_has_low_permission_for_job(job) %>
        <tr>
          <td><%= link_to job.title, job %></td>
          <% if job.project_manager %>
            <td><%= link_to "#{job.project_manager.last_name}, #{job.project_manager.first_name}", job.project_manager %></td>
          <% else %>
            <td><i>No project manager available</i></td>
          <% end %>
          <% if job.superintendent %>
            <td><%= link_to "#{job.superintendent.last_name}, #{job.superintendent.first_name}", job.superintendent %></td>
          <% else %>
            <td><i>No superintendent available</i></td>
          <% end %>
          <td><%= job.start_date %></td>
          <td><%= job.end_date || 'Ongoing' %></td>
          <td><%= job.tasks.length %></td>
          <% if current_user_has_high_permission_for_job(job) %>
            <td><%= link_to 'Edit', edit_job_path(job) %></td>
            <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% elsif !logged_in? %>
  <i>You are not logged in</i>
<% else %>
  <i>There are no jobs at the moment</i>
<% end %>
<br>

<% if current_user_has_high_permission_for_job %>
  <%= link_to 'New Job', new_job_path %>
<% end %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<% if current_user_has_high_permission_for_job %>
  <%= render 'form', job: @job %>
<% else %>
  <i>You are not allowed to create new jobs</i>
<% end %>
<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<% if current_user_has_low_permission_for_job(@job) %>
  <h2>
    <strong>Job:</strong>
    <%= @job.title %>
  </h2>
  <p>
    <strong>Superintendent:</strong>
    <% if @job.superintendent %>
      <%= link_to "#{@job.superintendent.last_name}, #{@job.superintendent.first_name}", @job.superintendent %>
    <% else %>
      <i>No superintendent exists</i>
    <% end %>
  </p>
  <p>
    <strong>Manager:</strong>
    <% if @job.project_manager %>
      <%= link_to "#{@job.project_manager.last_name}, #{@job.project_manager.first_name}", @job.superintendent %>
    <% else %>
      <i>No project manager exists</i>
    <% end %>
  </p>
  <p>
    <strong>Start date:</strong>
    <%= @job.start_date %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= @job.end_date || 'Ongoing' %>
  </p>

  <% if @job.tasks.any? %>
    <h2>Tasks</h2>

    <table>
      <thead>
        <tr>
          <th>Task</th>
          <th>SubContractor (<%= @job.sub_contractors.length %>)</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @job.tasks.each do |task| %>
          <tr>
            <td><%= link_to task.title, task %></td>
            <% if task.sub_contractor %>
              <td><%= link_to task.sub_contractor.name, task.sub_contractor %></td>
            <% else %>
              <td><i>No subcontractor exists for this task</i></td>
            <% end %>
            <td><%= link_to 'Show', task %></td>
            <td><%= link_to 'Edit', edit_task_path(task) %></td>
            <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <i>This job has no tasks</i>
  <% end %>
  <%= link_to 'New Task', new_task_path %>
  <br>
  <%= link_to 'All Jobs', jobs_path %>
  <br/>

  <%= link_to 'Edit', edit_job_path(@job) if current_user_has_high_permission_for_job %>
  <%= link_to 'Destroy', @job, method: :delete, data: { confirm: 'Are you sure?' } %>
<% else %>
  <i>You do not have permission to see this job</i><br>
  <%= link_to 'Jobs', jobs_path %>
<% end %>