config/routes.rb
Rails.application.routes.draw do
  resources :permission_codes
  resources :workers
  resources :tasks
  resources :jobs
  resources :users
  resources :sub_contractors

  root 'jobs#index'
  get '/login', to: 'sessions#new'
  post "/login", to: "sessions#create"
  delete "/login", to: "sessions#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/permission_code.rb
class PermissionCode < ApplicationRecord
  validates :body,
    presence: true,
    uniqueness: true

  validates :role,
    presence: true
end

app/controllers/permission_codes_controller.rb
class PermissionCodesController < ApplicationController
  before_action :set_permission_code, only: [:show, :edit, :update, :destroy]

  # GET /permission_codes
  # GET /permission_codes.json
  def index
    @permission_codes = PermissionCode.all
  end

  # GET /permission_codes/1
  # GET /permission_codes/1.json
  def show
  end

  # GET /permission_codes/new
  def new
    @permission_code = PermissionCode.new
  end

  # GET /permission_codes/1/edit
  def edit
  end

  # POST /permission_codes
  # POST /permission_codes.json
  def create
    @permission_code = PermissionCode.new(permission_code_params)

    respond_to do |format|
      if current_user_is_admin
        if @permission_code.save
          format.html { redirect_to @permission_code, notice: 'Permission code was successfully created.' }
          format.json { render :show, status: :created, location: @permission_code }
        else
          format.html { render :new }
          format.json { render json: @permission_code.errors, status: :unprocessable_entity }
        end
      else
        @permission_code.errors.add(:_, 'You are not allowed to create permission codes')

        format.html { render :index }
        format.json { render json: @permission_code.errors, status: :unauthorized }
      end
    end
  end

  # PATCH/PUT /permission_codes/1
  # PATCH/PUT /permission_codes/1.json
  def update
    respond_to do |format|
      if current_user_is_admin
        if @permission_code.update(permission_code_params)
          format.html { redirect_to @permission_code, notice: 'Permission code was successfully updated.' }
          format.json { render :show, status: :ok, location: @permission_code }
        else
          format.html { render :edit }
          format.json { render json: @permission_code.errors, status: :unprocessable_entity }
        end
      else
        @permission_code.errors.add(:_, 'You are not allowed to create permission codes')

        format.html { render :index }
        format.json { render json: @permission_code.errors, status: :unauthorized }
      end
    end
  end

  # DELETE /permission_codes/1
  # DELETE /permission_codes/1.json
  def destroy
    respond_to do |format|
      if current_user_is_admin
        @permission_code.destroy
        format.html { redirect_to permission_codes_url, notice: 'Permission code was successfully destroyed.' }
        format.json { head :no_content }
      else 
        @permission_code.errors.add(:_, 'You are not allowed to create permission codes')

        format.html { render :index }
        format.json { render json: @permission_code.errors, status: :unauthorized }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permission_code
      return nil if !current_user_is_admin
      
      @permission_code = PermissionCode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def permission_code_params
      params.require(:permission_code).permit(:body, :role)
    end
end

app/helpers/permission_codes_helper.rb
module PermissionCodesHelper
end

app/views/permission_codes/_form.html.erb
<%= form_with(model: permission_code, local: true) do |form| %>
  <% if permission_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(permission_code.errors.count, "error") %> prohibited this permission_code from being saved:</h2>

      <ul>
      <% permission_code.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_user_is_admin %>
    <div class="field">
      <%= form.label :body %>
      <%= form.text_field :body %>
    </div>

    <div class="field">
      <%= form.label :role %>
      <%= form.select :role do %>
        <% [['Admin', 1], ['Manager', 2], ['SuperIntendent', 3]].each do |c| -%>
          <%= content_tag(:option, c.first, value: c.last) %>
        <% end %>
      <% end %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% else %>
    <i>You do not have permission to view this page</i>
  <% end %>
<% end %>

app/views/permission_codes/edit.html.erb
<h1>Editing Permission Code</h1>

<%= render 'form', permission_code: @permission_code %>

<%= link_to 'Show', @permission_code %> |
<%= link_to 'Back', permission_codes_path %>

app/views/permission_codes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Permission Codes</h1>

<% if current_user_is_admin %>
  <table>
    <thead>
      <tr>
        <th>Body</th>
        <th>Role</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @permission_codes.each do |permission_code| %>
        <tr>
          <td><%= permission_code.body %></td>
          <td><%= readable_role(permission_code.role) %></td>
          <td><%= link_to 'Show', permission_code %></td>
          <td><%= link_to 'Edit', edit_permission_code_path(permission_code) %></td>
          <td><%= link_to 'Destroy', permission_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Permission Code', new_permission_code_path %>
<% else %>
  <i>You do not have permission to see this page</i>
  <br>
  <%= link_to 'Back home', jobs_path %>
<% end %>

app/views/permission_codes/new.html.erb
<h1>New Permission Code</h1>

<%= render 'form', permission_code: @permission_code %>

<%= link_to 'Back', permission_codes_path %>

app/views/permission_codes/show.html.erb
<% if current_user_is_admin %>
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Code:</strong>
    <%= @permission_code.body %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= readable_role(@permission_code.role) %>
  </p>

  <%= link_to 'Edit', edit_permission_code_path(@permission_code) %> |
  <%= link_to 'Back to permission codes', permission_codes_path %>
<% else %>
  <i>You do not have permission to see this page</i>
  <br>
  <%= link_to 'Back home', jobs_path %>
<% end %>